MyEventsView Created.
xubosen/CSC207-Project-Group-262 pull request #45
Opened 2023-11-14 17:53 UTC by Fourstarfish

MyEventsView created; main and DashboardView edited to account for its creation.

2023-11-15 23:43 UTC, Fourstarfish commented
New commit added. This one deals with EventAddition (which is the adding people to Event use case). Still needs some work particularly the logic of the use case.

2023-11-17 23:04 UTC, xubosen commented on src/app/Main.java
> +        DashboardView dashboardView = new DashboardView(viewManagerModel, leaveRequestView.viewName, myCoursesView.viewName, myEventsView.viewName);
Interesting choice to link "my events" page to dashboard. Although we haven't discussed this yet, since events are grouped into courses, it might be better to link it not to dashboard but to "my courses".

2023-11-17 23:11 UTC, xubosen commented on src/app/Main.java
> +        // Initialize EventAdditionView
Our main function is getting a bit long and hard to read, so perhaps it is better to separate this into its own separate private static method?

2023-11-17 23:14 UTC, xubosen commented on src/data_access/HardCodedDAO.java
This file is for testing and demo purposes only and will be deleted once our database access module is complete, so we don't really need to commit it to main.

2023-11-17 23:16 UTC, xubosen commented on src/interface_adapter/EventAdditionPresenter.java
> +        System.out.println(outputData.getMessage());
Don't forget to delete the debugging sout statements!

2023-11-17 23:20 UTC, xubosen commented on src/interface_adapter/EventAdditionViewModel.java
> +        System.out.println(state.getUserInvited());
As before, don't forget to delete the debugging sout statements!

2023-11-17 23:31 UTC, xubosen commented on src/view/EventAdditionView.java
> +            String courseCode = "CSC207";
Since you are adding to an event, not to a course, this should be changed to the event ID.

2023-11-17 23:32 UTC, xubosen commented on src/view/EventAdditionView.java
> +            System.out.println(inviteeID);
Remove sout statement!

2023-11-17 23:33 UTC, xubosen commented on src/view/EventAdditionView.java
> +            eventAdditionController.addEmployeeToEvent(inviteeID, courseCode);
See above comment on event ID and not course code.

2023-11-17 23:36 UTC, xubosen commented on src/view/EventAdditionView.java
> +        System.out.println("Listener is triggered");
Sout spotted!

2023-11-17 23:38 UTC, xubosen commented on src/view/MyEventsView.java
Current view mainly for testing purposes. Will probably be redesigned in the future.

2023-11-17 23:46 UTC, xubosen requested changes
Please see comments for detailed review!

It is also a little unclear whether testing has been conducted and to what extent (e.g. does the code run? does it work as expected?). I would recommend adding unit testing to every method that is not rudimentary. 

Lastly, documentation can also be improved, especially for interactors, when representational invariants are being invoked.

2023-11-17 23:48 UTC, xubosen commented on src/use_case/EventAdditionInteractor.java
In this interactor, I think you are missing the part where we check if the user is in the course that the event is from. Since we are typing the userID, currently this allows for users that are not in the course to be added to the event.

2023-11-18 01:27 UTC, xubosen approved these changes
Comments fixed. Further testing will be made according to in-person discussion.

2023-11-18 01:27 UTC, merged