DAO created for specific entities.
xubosen/CSC207-Project-Group-262 pull request #56
Opened 2023-11-23 01:27 UTC by alexgphan

Currently I've tested pulling information and letting it create instances of the classes from that and it works fine but I have yet to try saving the info from main. I was able to practice saving information from another testfile but not with the current completed ones.

2023-11-23 01:49 UTC, xubosen commented on src/app/Main.java
> +            throw new RuntimeException(e);
Would it be better if we defined our own exception rather than using a runtime exception?

2023-11-23 01:51 UTC, xubosen commented on src/app/Main.java
> +        FileCourseDataAccessObject courseDataAccessObject = new FileCourseDataAccessObject(employeeDAO1);
Should not need the "1" after employeeDAO1, since we only have 1.

2023-11-23 01:52 UTC, xubosen commented on src/app/Main.java
> +        // Pull from the employees collection to make in memory employees.
Is it possible to split this into a helper method? Our main is getting quite clustered.

2023-11-23 01:55 UTC, xubosen commented on build.gradle
It is possible to write a documentation for what this file does? I'm a bit confused.

2023-11-23 01:58 UTC, xubosen commented on src/data_access/FileCourseDataAccessObject.java
> +import java.util.*;
We probably don't need everything in util. Would it be better if we imported just what we used?

2023-11-23 01:59 UTC, xubosen commented on src/data_access/FileCourseDataAccessObject.java
> +    public static final HashMap<String, Course> courses = new HashMap<>();
Should this be private?

2023-11-23 02:01 UTC, xubosen commented on src/data_access/FileCourseDataAccessObject.java
> +        String uri = "mongodb+srv://shinyarkeus:KWhU7JJK5BiBcQ0c@projecthr.u9tq0zb.mongodb.net/?retryWrites=true&w=majority";
You probably shouldn't include this in the file. Try saving it in another file and then importing it somehow? 

Also, I'm pretty sure this shouldn't be in the repository at all. I think it's better if we each have our private copy of it instead.

2023-11-23 02:06 UTC, xubosen commented on src/data_access/FileCourseDataAccessObject.java
> +            MongoDatabase db = mongoClient.getDatabase("hrsystem_database");
"hrsystem_database" should probably be a constant variable or something you import from a separate file (see comment on saving the uri in another file)

2023-11-23 02:07 UTC, xubosen commented on src/data_access/FileEmployeeDataAccessObject.java
> +//        databaseFiles = new File(databasePath);
Is this meant to be commented out? If yes, would it be better if we just deleted it?

2023-11-23 02:08 UTC, xubosen commented on src/data_access/FileEmployeeDataAccessObject.java
> +    public final HashMap<String, Employee> accounts = new HashMap<>();
Is this supposed to be public?

2023-11-23 02:08 UTC, xubosen commented on src/data_access/FileEmployeeDataAccessObject.java
> +        String uri = "mongodb+srv://shinyarkeus:KWhU7JJK5BiBcQ0c@projecthr.u9tq0zb.mongodb.net/?retryWrites=true&w=majority";
Please see previous comment on storing the uri!

2023-11-23 02:08 UTC, xubosen commented on src/data_access/FileEmployeeDataAccessObject.java
> +        String uri = "mongodb+srv://shinyarkeus:KWhU7JJK5BiBcQ0c@projecthr.u9tq0zb.mongodb.net/?retryWrites=true&w=majority";
Please see previous comment on storing the uri!

2023-11-23 02:09 UTC, xubosen commented on src/data_access/FileEmployeeDataAccessObject.java
> +            MongoDatabase db = mongoClient.getDatabase("hrsystem_database");
Please see previous comment on hard coding things like "hrsystem_database" and "employees"!

2023-11-23 02:09 UTC, xubosen commented on src/data_access/FileEmployeeDataAccessObject.java
> +    private void save() {
Could this method be split into more helper methods?

2023-11-23 02:10 UTC, xubosen commented on src/data_access/FileEventDataAccessObject.java
> +        String uri = "mongodb+srv://shinyarkeus:KWhU7JJK5BiBcQ0c@projecthr.u9tq0zb.mongodb.net/?retryWrites=true&w=majority";
Please see previous comment on storing the uri!

2023-11-23 02:10 UTC, xubosen commented on src/data_access/FileEventDataAccessObject.java
> +        String uri = "mongodb+srv://shinyarkeus:KWhU7JJK5BiBcQ0c@projecthr.u9tq0zb.mongodb.net/?retryWrites=true&w=majority";
Please see previous comment on storing the uri!

2023-11-23 02:10 UTC, xubosen commented on src/data_access/FileEventDataAccessObject.java
> +    public static final HashMap<String, Event> events = new HashMap<>();
I don't think this is supposed to be public?

2023-11-23 02:11 UTC, xubosen commented on src/data_access/FileEventDataAccessObject.java
> +    private void save() {
Could this be split into more helper methods for testing purposes?

2023-11-23 02:11 UTC, xubosen commented on src/data_access/FileSessionDataAccessObject.java
> +        String uri = "mongodb+srv://shinyarkeus:KWhU7JJK5BiBcQ0c@projecthr.u9tq0zb.mongodb.net/?retryWrites=true&w=majority";
Please see previous comment on storing the uri!

2023-11-23 02:11 UTC, xubosen commented on src/data_access/FileSessionDataAccessObject.java
> +    public static final HashMap<String, ClassSession> sessions = new HashMap<>();
Was this meant to be public?

2023-11-23 02:11 UTC, xubosen commented on src/data_access/FileSessionDataAccessObject.java
> +            MongoDatabase db = mongoClient.getDatabase("hrsystem_database");
Please see previous comment on hardcoding "hrsystem_database" and "sessions"!

2023-11-23 02:12 UTC, xubosen commented on src/data_access/FileSessionDataAccessObject.java
> +        String uri = "mongodb+srv://shinyarkeus:KWhU7JJK5BiBcQ0c@projecthr.u9tq0zb.mongodb.net/?retryWrites=true&w=majority";
Please see previous comment on storing the uri!

2023-11-23 02:12 UTC, xubosen commented on src/data_access/FileSessionDataAccessObject.java
> +            MongoDatabase db = mongoClient.getDatabase("hrsystem_database");
Please see previous comment on hardcoding "hrsystem_database" and "sessions"!

2023-11-23 02:13 UTC, alexgphan commented on src/app/Main.java
> +        FileCourseDataAccessObject courseDataAccessObject = new FileCourseDataAccessObject(employeeDAO1);
Will change this now, was like that because of HardCodedDAO.

2023-11-23 02:14 UTC, xubosen commented on src/data_access/JsonToCourse.java
> +    //    public static void main(String[] args) {
Testing code is best deleted when merging.

2023-11-23 02:17 UTC, xubosen commented on src/data_access/JsonToCourse.java
> +            String courseName = obj.getString("course_name");
When we rely on how the json file is formatted, we should probably use constants or import them from another file.

2023-11-23 02:17 UTC, alexgphan commented on src/app/Main.java
> +        // Pull from the employees collection to make in memory employees.
Yes, I can split it up into one big helper probably called DAOCreator and then mini helpers inside to create each one.

2023-11-23 02:18 UTC, xubosen commented on src/data_access/JsonToEmployee.java
> +//        Employee employee;
Was this meant to be commented our? If so, would it be better to just delete it?

2023-11-23 02:18 UTC, xubosen commented on src/data_access/JsonToEmployee.java
> +        String userID = obj.getString("userID");
Please see comment on relying on how the json is formatted!

2023-11-23 02:19 UTC, xubosen commented on src/data_access/JsonToEmployee.java
> +//    public static void main(String[] args) {
Code for testing purposes is best deleted or turned into unit tests.

2023-11-23 02:19 UTC, xubosen commented on src/data_access/JsonToEvent.java
> +//    public static void main(String[] args) {
Code for testing purposes is best deleted or turned into unit tests.

2023-11-23 02:20 UTC, xubosen commented on src/data_access/JsonToEvent.java
> +        String name = obj.getString("name");
Please see comment on relying on how the json file is formatted!

2023-11-23 02:20 UTC, xubosen commented on src/data_access/JsonToSession.java
> +        String sessionName = obj.getString("session_name");
Please see comment on relying on how the json file is formatted!

2023-11-23 02:22 UTC, xubosen commented on src/data_access/JsonToEvent.java
> +    public Event convert() {
Could this be split into more helper methods?

2023-11-23 02:23 UTC, xubosen commented on src/data_access/JsonToSession.java
> +    public ClassSession convert() {
This method is best split into several helper methods.

2023-11-23 02:23 UTC, xubosen commented on src/entity/Employee.java
Is this meant to be commited?

2023-11-23 02:27 UTC, alexgphan commented on src/data_access/FileCourseDataAccessObject.java
> +import java.util.*;
I should because it would more clear what we are using from the library.

2023-11-23 02:27 UTC, xubosen requested changes
Please see more details for in-line comments! 

Also, since these are rather complicated classes, there should probably be unit tests testing most if not all of the helper methods of each of these classes, just to make sure they work.

2023-11-23 02:31 UTC, alexgphan commented on src/entity/Employee.java
No, it was just a really outdated todo.

2023-11-23 02:53 UTC, xubosen reviewed
Another note is that currently this Data Access implementation doesn't abide by clean architecture. 

I think a way to edit this is to split the current "DataAccessObject" classes into a "data access" version that just retrieves the JSON objects from mongoDB and an "interactor" version that takes those strings and create the actual entities.

(You could even turn the JSON objects into an intermediate data package if you like, similar to how we use input data and output data for use cases)

2023-11-28 01:13 UTC, xubosen approved these changes
Clean architecture problem still exists, but most previous issues are fixed. Testing for data access is complete. Due to time constraints, merging is done although content is yet imperfect. More fixes to be done.

2023-11-28 01:13 UTC, merged